FROM ruby:3.0.3-alpine

RUN apk update && apk upgrade && \
    apk add --update nodejs yarn git build-base libxml2 libxml2-dev libxml2-utils libxslt-dev tzdata && \
    apk add libc6-compat sassc libsass && \
    apk add postgresql-dev postgresql-client && \
    rm -rf /var/cache/apk/*

ENV HOME /app
ENV RAILS_ENV production
ENV RAILS_SERVE_STATIC_FILES true
ENV SECRET_KEY_BASE abcdefgh12345678

WORKDIR $HOME

# Install gems
ADD .ruby-version $HOME/
ADD Gemfile* $HOME/
RUN gem update bundler
# speed up install of nokogiri gem
RUN bundle config --local build.nokogiri --use-system-libraries
RUN bundle config set without 'development test'
RUN bundle install 

# Install npm packages
ADD package.json $HOME
ADD yarn.lock $HOME
RUN yarn install

# Add the app code
COPY . $HOME

RUN bundle exec rake assets:precompile
