name: Docker amd64

# on:
#   push:
#     branches: [ main ]
#     tags:
#       - '*'
on: workflow_dispatch

jobs:
  docker:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: rlespinasse/github-slug-action@v2.x
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u doerfli --password-stdin
      - run: docker build -f Dockerfile-prod -t docker.pkg.github.com/doerfli/shelly-temp/shelly-temp:${{ env.GITHUB_REF_SLUG }} .
      - run: docker push docker.pkg.github.com/doerfli/shelly-temp/shelly-temp:${{ env.GITHUB_REF_SLUG }}
