name: Docker

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  docker:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: rlespinasse/github-slug-action@v2.x
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u doerfli --password-stdin
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest      
      - run: docker buildx build -f Dockerfile-prod -t docker.pkg.github.com/doerfli/shelly-temp/shelly-temp:${{ env.GITHUB_REF_SLUG }} --platform linux/amd64,linux/arm/v7,linux/arm64 .
      - run: docker push docker.pkg.github.com/doerfli/shelly-temp/shelly-temp:${{ env.GITHUB_REF_SLUG }}
